### ISSUE TITLE
Use 'request review' instead of 'assignee' when assigning tutors to PRs

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/cs2103-pr-bot#18]
Current: use the `assignee` field to assign tutors to PRs
Suggested: use the `request` review instead? Or both?

**Comment by louislai** [comment]
I find `request review` more suitable as well. `assignee` refers to someone writing the codes in the PR, or someone completing the feature in the PR, which would be the student. Opinion on StackOverflow https://stackoverflow.com/questions/41087206/on-github-whats-the-difference-between-reviewer-and-assignee

**Comment by damithc** [comment]
In our case we'll probably use `assignee` to be the tutor in charge of that student and `reviewer` to be the tutor that reviews the PR. This is because in some tutorials PRs will be reviewed by the co-tutor (not the main tutor). We can identify the author of the PR using the `author` field.

**Comment by louislai** [comment]
that sounds reasonable 👍

**Comment by mauris** [comment]
this likely requires a change in the [underlying wrapper library](https://github.com/mauris/accuser). will do the change and update here.

**Comment by louislai** [comment]
> this likely requires a change in the underlying wrapper library. will do the change and update here.

thanks @mauris 👍 . do you still prefer `accuser` to be maintained separately under your account?

**Comment by madsonic** [comment]
> this likely requires a change in the underlying wrapper library. will do the change and update here.
iirc, the 'reviewer' field is recently added by Github

I don't mind working on `accuser` if it is a necessary for something to work here too!

**Comment by louislai** [comment]
@damithc @madsonic @mauris I did some further digging on request reviewer api. Apparently the API for this particular feature is still experimental and not stable enough yet for production use. Extract from [github docs](https://developer.github.com/v3/pulls/review_requests/)

>Warning: The API may change without advance notice during the preview period. Preview features are not supported for production use. If you experience any issues, contact GitHub support.

So my opinion is we leave this feature on hold until (maybe) next year, when the preview period is over :)

**Comment by damithc** [comment]
> So my opinion is we leave this feature on hold until (maybe) next year, when the preview period is over :)

I'm fine with that.

**Comment by louislai** [comment]
ok 👍

**Comment by louislai** [comment]
@mauris just a head up. We will go forward with this feature, and also make a fork of `accuser` under 2103 org, to offload the maintenance to us :D

**Comment by louislai** [comment]
@okkhoy can you help me fork `accuser` to 2103 org, and give me write permission?

**Comment by louislai** [comment]
shipped 🚢
