### ISSUE TITLE
Mu templating issue

### ISSUE THREAD

**Issue by louislai** [nus-cs2103/cs2103-pr-bot#21]
I am convinced there are issues with using the rendered output of `mu.render` as argument to `accuser.comment`, which causes exceptions to be thrown. Specifically, this happens for [this line]( https://github.com/nus-cs2103/cs2103-pr-bot/blob/master/src/seedu.js#L29) and [this line](https://github.com/nus-cs2103/cs2103-pr-bot/blob/master/src/semester.js#L23). 

@madsonic can also replicate this issue. When using a bad title for a PR to semestral repo, the line 23 of `semester.js` will be called and cause this exception. Stack trace is attached [here](https://pastebin.com/6dbFcPyv)

**Comment by louislai** [comment]
@mauris wonder if you can replicate this as well :)

**Comment by mauris** [comment]
I think we can just change the code according to the API specifications for Mu since it specified Stream; rather than implying that it is possible on some platforms / versions it can be cast into string.

**Comment by louislai** [comment]
Do you happen to know how to cast a Stream explicitly into string? The README here https://github.com/raycmorgan/Mu does not seem to mention it.
