### ISSUE TITLE
FormatCheckRequested label not removed on correcting the PR title format

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/cs2103-pr-bot#6]
There is a message that says "removed format check requested label" however, the label persists

**Comment by mauris** [comment]
I think it is likely a problem on Github's end. I've done a clean up on the duplicate labels and labels that are supposed to be removed. We'll observe and see if it is indeed a problem coming from the bot.

**Comment by okkhoy** [comment]
sure! that works :-)
