### ISSUE TITLE
duplicate labels in repo after running bot

### ISSUE THREAD

**Issue by madsonic** [nus-cs2103/cs2103-pr-bot#60]
duplicated labels can exist in the repo after running which can confuse the bot as labels are considered distinct despite same label name. 

need some investigation work here

**Comment by mauris** [comment]
Wasn't this brought up in #49 and #8? same issue?

**Comment by mauris** [comment]
From #49, you said: "labels need to exists before adding labels to PR otherwise it would cause a strange bug with multiple duplicate labels on github."

**Comment by louislai** [comment]
@madsonic should create the labels first. Otherwise you can just remove the duplicate label from the repo, should work :D

**Comment by madsonic** [comment]
@mauris my bad i think i should have reopened #8 instead or just leave this as `wont fix`. @louislai all the labels already existed before running the bot which was why I raised this up again
