### ISSUE TITLE
Assignment removal

### ISSUE THREAD

**Issue by madsonic** [nus-cs2103/cs2103-pr-bot#63]
This has been happening after assignment of 2 users has been implemented. Strangely, no unassign code has been used at all!

![screen shot 2018-02-11 at 11 58 14 pm](https://user-images.githubusercontent.com/437672/36075274-8b1e17c8-0f87-11e8-8d66-09d2c272ccf1.png)

**Comment by okkhoy** [comment]
https://github.com/nus-cs2103-AY1718S2/addressbook-level2/pull/629

**Comment by louislai** [comment]
Closing this for now
