### ISSUE TITLE
Seems like the bot is not ignoring a PR already assigned with FormatCheckRequested label

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/cs2103-pr-bot#7]
See PR for example: https://github.com/nus-cs2103-AY1617S2/addressbook-level1/pull/219

**Comment by mauris** [comment]
The bot should not ignore a PR with FormatCheckRequested label because once the student performs edit on the PR, the bot will notice that the title format is valid, then remove the label. (can't recall what was the exact issue with this report, so i'll close it for now)
